//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "EditingControlFrame")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    #[sea_orm(unique)]
    pub frame_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::control_frame::Entity",
        from = "Column::FrameId",
        to = "super::control_frame::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ControlFrame,
}

impl Related<super::control_frame::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ControlFrame.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
