//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "LEDEffect")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "name")]
    pub name: String,
    #[sea_orm(unique_key = "name")]
    pub model_id: i32,
    #[sea_orm(unique_key = "name")]
    pub part_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::control_data::Entity")]
    ControlData,
    #[sea_orm(has_one = "super::editing_led_effect::Entity")]
    EditingLedEffect,
    #[sea_orm(has_many = "super::led_effect_state::Entity")]
    LedEffectState,
    #[sea_orm(
        belongs_to = "super::model::Entity",
        from = "Column::ModelId",
        to = "super::model::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Model,
    #[sea_orm(
        belongs_to = "super::part::Entity",
        from = "Column::PartId",
        to = "super::part::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Part,
}

impl Related<super::control_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ControlData.def()
    }
}

impl Related<super::editing_led_effect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditingLedEffect.def()
    }
}

impl Related<super::led_effect_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedEffectState.def()
    }
}

impl Related<super::model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Model.def()
    }
}

impl Related<super::part::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Part.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
