//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "LEDBulb")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub control_id: i32,
    pub position: i32,
    pub color_id: i32,
    pub alpha: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::control_data::Entity",
        from = "Column::ControlId",
        to = "super::control_data::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ControlData,
}

impl Related<super::control_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ControlData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
