//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "PositionFrame")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub start: i32,
    pub meta_rev: i32,
    pub data_rev: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::editing_position_frame::Entity")]
    EditingPositionFrame,
    #[sea_orm(has_many = "super::position_data::Entity")]
    PositionData,
}

impl Related<super::editing_position_frame::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditingPositionFrame.def()
    }
}

impl Related<super::position_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionData.def()
    }
}

impl Related<super::dancer::Entity> for Entity {
    fn to() -> RelationDef {
        super::position_data::Relation::Dancer.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::position_data::Relation::PositionFrame.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
