const RED_MAPPING = {
  MAPB: {
    Mask: "B_MASK",
    Eyes: "B_MASK",
    Collar: "B_MASK",
    Wrist_R: "B_R_FOREARM",
    Wrist_L: "B_L_FOREARM",
    Capacitor_1: "B_BELT",
    Capacitor_2: "B_BELT",
    Tie: "B_BELT",
    Surcoat: "B_L_PANT",
    Chest: "B_BODY",
    Boot_R: "B_R_LEG",
    Boot_L: "B_L_LEG",
    Rune: "B_BODY",
    Rune_R: "B_R_PANT",
    Rune_L: "B_L_PANT",
    Arm_R: "B_R_ARM",
    Arm_L: "B_L_ARM",
    // Chest_LED: "Chest_LED",
    // Eyes_LED: "Eyes_LED",
    // Wrist_R_LED: "Wrist_R_LED",
    // Wrist_L_LED: "Wrist_L_LED",
    // Shoe_R_LED: "Shoe_R_LED",
    // Shoe_L_LED: "Shoe_L_LED",
    color: {
      r: 0.019768331199884415,
      g: 1,
      b: 1,
    },
  },
  MAPG: {
    Mask: "G_MASK",
    Eyes: "G_MASK",
    Collar: "G_MASK",
    Wrist_R: "G_R_FOREARM",
    Wrist_L: "G_L_FOREARM",
    Capacitor_1: "G_BELT",
    Capacitor_2: "G_BELT",
    Tie: "G_BELT",
    Surcoat: "G_L_PANT",
    Chest: "G_BODY",
    Boot_R: "G_R_LEG",
    Boot_L: "G_L_LEG",
    Rune: "G_BODY",
    Rune_R: "G_R_PANT",
    Rune_L: "G_L_PANT",
    Arm_R: "G_R_ARM",
    Arm_L: "G_L_ARM",
    // Chest_LED: "Chest_LED",
    // Eyes_LED: "Eyes_LED",
    // Wrist_R_LED: "Wrist_R_LED",
    // Wrist_L_LED: "Wrist_L_LED",
    // Shoe_R_LED: "Shoe_R_LED",
    // Shoe_L_LED: "Shoe_L_LED",
    color: {
      r: 1,
      g: 1,
      b: 0.17821459472179413,
    },
  },
  MAPS: {
    Mask: "S_HAT",
    Eyes: "S_GLASSES",
    Collar: "S_COLLAR",
    Wrist_R: "S_R_HAND",
    Wrist_L: "B_L_HAND",
    Capacitor_1: "S_BELT",
    Capacitor_2: "S_BELT",
    Tie: "S_BELT",
    Surcoat: "S_L_PANT",
    Chest: "S_NECKTIE",
    Boot_R: "S_R_PANT",
    Boot_L: "S_L_PANT",
    Rune: "S_NECKTIE",
    Rune_R: "S_R_PANT",
    Rune_L: "S_L_PANT",
    Arm_R: "S_R_HAND",
    Arm_L: "S_L_HAND",
    // Chest_LED: "Chest_LED",
    // Eyes_LED: "Eyes_LED",
    // Wrist_R_LED: "Wrist_R_LED",
    // Wrist_L_LED: "Wrist_L_LED",
    // Shoe_R_LED: "Shoe_R_LED",
    // Shoe_L_LED: "Shoe_L_LED",
    color: {
      r: 1,
      g: 0.017767056822776794,
      b: 1,
    },
  },
};

const YELLOW_MAPPING = {
  MAPG: {
    Visor: "G_MASK",
    Ear_R: "G_MASK",
    Ear_L: "G_MASK",
    Arm_R: "G_R_ARM",
    Arm_L: "G_L_ARM",
    Shoulder_R: "G_R_ARM",
    Shoulder_L: "G_L_ARM",
    CollarBone_R: "G_BODY",
    CollarBone_L: "G_BODY",
    Chest: "G_BODY",
    LymphaticDuct_R: "G_BODY",
    LymphaticDuct_L: "G_BODY",
    Waist_R: "G_BELT",
    Waist_L: "G_BELT",
    Thigh_R: "G_R_PANT",
    Thigh_L: "G_L_PANT",
    Calf_R: "G_R_SHOE",
    Calf_L: "G_L_SHOE",
    // Visor_LED: "Visor_LED",
    // CollarBone_R_LED: "CollarBone_R_LED",
    // CollarBone_L_LED: "CollarBone_L_LED",
    // Shoulder_R_LED: "Shoulder_R_LED",
    // Shoulder_L_LED: "Shoulder_L_LED",
    // Hand_R_LED: "Hand_R_LED",
    // Hand_L_LED: "Hand_L_LED",
    // Shoe_R_LED: "Shoe_R_LED",
    // Shoe_L_LED: "Shoe_L_LED",
    color: {
      r: 1,
      g: 1,
      b: 0.17821459472179413,
    },
  },
  MAPB: {
    Visor: "B_MASK",
    Ear_R: "B_MASK",
    Ear_L: "B_MASK",
    Arm_R: "B_R_ARM",
    Arm_L: "B_L_ARM",
    Shoulder_R: "B_R_ARM",
    Shoulder_L: "B_L_ARM",
    CollarBone_R: "B_BODY",
    CollarBone_L: "B_BODY",
    Chest: "B_BODY",
    LymphaticDuct_R: "B_BODY",
    LymphaticDuct_L: "B_BODY",
    Waist_R: "B_BELT",
    Waist_L: "B_BELT",
    Thigh_R: "B_R_PANT",
    Thigh_L: "B_L_PANT",
    Calf_R: "B_R_SHOE",
    Calf_L: "B_L_SHOE",
    // Visor_LED: "Visor_LED",
    // CollarBone_R_LED: "CollarBone_R_LED",
    // CollarBone_L_LED: "CollarBone_L_LED",
    // Shoulder_R_LED: "Shoulder_R_LED",
    // Shoulder_L_LED: "Shoulder_L_LED",
    // Hand_R_LED: "Hand_R_LED",
    // Hand_L_LED: "Hand_L_LED",
    // Shoe_R_LED: "Shoe_R_LED",
    // Shoe_L_LED: "Shoe_L_LED",
    color: {
      r: 0.019768331199884415,
      g: 1,
      b: 1,
    },
  },
  MAPS: {
    Visor: "S_GLASSES",
    Ear_R: "S_HAT",
    Ear_L: "S_HAT",
    Arm_R: "S_R_HAND",
    Arm_L: "S_L_HAND",
    Shoulder_R: "S_R_HAND",
    Shoulder_L: "S_L_HAND",
    CollarBone_R: "S_BELT",
    CollarBone_L: "S_BELT",
    Chest: "S_NECKTIE",
    LymphaticDuct_R: "S_BELT",
    LymphaticDuct_L: "S_BELT",
    Waist_R: "S_BELT",
    Waist_L: "S_BELT",
    Thigh_R: "S_R_PANT",
    Thigh_L: "S_L_PANT",
    Calf_R: "S_R_SHOE",
    Calf_L: "S_L_SHOE",
    // Visor_LED: "Visor_LED",
    // CollarBone_R_LED: "CollarBone_R_LED",
    // CollarBone_L_LED: "CollarBone_L_LED",
    // Shoulder_R_LED: "Shoulder_R_LED",
    // Shoulder_L_LED: "Shoulder_L_LED",
    // Hand_R_LED: "Hand_R_LED",
    // Hand_L_LED: "Hand_L_LED",
    // Shoe_R_LED: "Shoe_R_LED",
    // Shoe_L_LED: "Shoe_L_LED",
    color: {
      r: 1,
      g: 0.017767056822776794,
      b: 1,
    },
  },
};

const BLUE_MAPPING = {};

const OLD_PART_NAMES = {
  ELPARTS: {
    G_MASK: {},
    G_R_ARM: {},
    G_L_ARM: {},
    G_R_FOREARM: {},
    G_L_FOREARM: {},
    G_BELT: {},
    G_BODY: {},
    G_R_LEG: {},
    G_L_LEG: {},
    G_R_PANT: {},
    G_L_PANT: {},
    G_R_SHOE: {},
    G_L_SHOE: {},

    S_HAT: {},
    S_GLASSES: {},
    S_COLLAR: {},
    S_R_HAND: {},
    S_L_HAND: {},
    S_R_COAT: {},
    S_L_COAT: {},
    S_NECKTIE: {},
    S_BELT: {},
    S_R_PANT: {},
    S_L_PANT: {},
    S_R_SHOE: {},
    S_L_SHOE: {},
  },
};

const ALL_MAPPING = {
  YELLOW_MAPPING,
  RED_MAPPING,
  BLUE_MAPPING,
};

export default ALL_MAPPING;
