import { ModelPinMapTable } from "@/schema/PinMapTable";

// The pinmap template for each model
export const characterPinMapTable: ModelPinMapTable = {
  hunter: {
    fps: 30,
    OFPARTS: {
      collar: 0,
      shirt_left_in: 1,
      shirt_left_out: 2,
      arm_left_out: 3,
      arm_left_in: 4,
      cloak_hat_top: 7,
      cloak_hat_edge: 8,
      belt_out: 9,
      cloak_collar_button: 10,
      shirt_right_in: 11,
      shirt_right_out: 12,
      arm_right_out: 13,
      arm_right_in: 14,
      shirt_button_top: 16,
      shirt_button_mid: 17,
      shirt_button_bottom: 18,
      belt_in: 19,
      leg_left_in: 20,
      leg_left_out: 21,
      cloak_left_out: 22,
      cloak_left_in: 23,
      cloak_bottom_left_out: 24,
      cloak_bottom_left_in: 25,
      shoes_left_top: 26,
      shoes_left_bottom: 27,
      leg_right_in: 30,
      leg_right_out: 31,
      cloak_right_out: 32,
      cloak_right_in: 33,
      cloak_bottom_right_out: 34,
      cloak_bottom_right_in: 35,
      shoes_right_top: 36,
      shoes_right_bottom: 37,
    },
    LEDPARTS: {
      glove_left_LED: { id: 1, len: 36 },
      glove_right_LED: { id: 2, len: 36 },
      wrist_left_LED: { id: 3, len: 18 },
      wrist_right_LED: { id: 4, len: 18 },
      bearpalm_LED: { id: 5, len: 9 },
    },
    LEDPARTS_MERGE: {},
  },
  main_boy: {
    fps: 30,
    OFPARTS: {
      collar: 0,
      shirt_left_in: 1,
      shirt_left_out: 2,
      arm_left_out: 3,
      arm_left_in: 4,
      cloak_hat_top: 7,
      cloak_hat_edge: 8,
      belt_out: 9,
      cloak_collar_button: 10,
      shirt_right_in: 11,
      shirt_right_out: 12,
      arm_right_out: 13,
      arm_right_in: 14,
      shirt_button_top: 16,
      shirt_button_mid: 17,
      shirt_button_bottom: 18,
      belt_in: 19,
      leg_left_in: 20,
      leg_left_out: 21,
      cloak_left_out: 22,
      cloak_left_in: 23,
      cloak_bottom_left_out: 24,
      cloak_bottom_left_in: 25,
      shoes_left_top: 26,
      shoes_left_bottom: 27,
      leg_right_in: 30,
      leg_right_out: 31,
      cloak_right_out: 32,
      cloak_right_in: 33,
      cloak_bottom_right_out: 34,
      cloak_bottom_right_in: 35,
      shoes_right_top: 36,
      shoes_right_bottom: 37,
    },
    LEDPARTS: {
      mask_LED: { id: 0, len: 8 },
      glove_left_LED: { id: 1, len: 36 },
      glove_right_LED: { id: 2, len: 36 },
      bearpalm_LED: { id: 3, len: 9 },
      shoulder_left_LED: { id: 4, len: 12 },
      shoulder_right_LED: { id: 5, len: 12 },
      wrist_left_LED: { id: 6, len: 27 },
      wrist_right_LED: { id: 7, len: 18 },
    },
    LEDPARTS_MERGE: {},
  },
  main_girl: {
    fps: 30,
    OFPARTS: {
      cloak_out: 0,
      cloak_arm_left: 1,
      arm_left_out: 2,
      arm_left_in: 3,
      arm_cuff_left: 4,
      shirt_left_out: 5,
      shirt_left_mid: 6,
      shirt_left_in: 7,
      belt_left: 8,
      cloak_left_in: 9,
      cross: 10,
      cloak_arm_right: 11,
      arm_right_out: 12,
      arm_right_in: 13,
      arm_cuff_right: 14,
      shirt_right_out: 15,
      shirt_right_mid: 16,
      shirt_right_in: 17,
      belt_right: 18,
      cloak_right_in: 19,
      skirt_bottom_bottom_front: 20,
      skirt_left_out: 21,
      skirt_left_mid: 22,
      skirt_left_in: 23,
      leg_left_out: 24,
      leg_left_in: 25,
      shoes_left_bottom: 26,
      shoes_left_ankle: 27,
      shoes_left_front: 28,
      skirt_bottom_bottom_back: 29,
      skirt_bottom_top_front: 30,
      skirt_right_out: 31,
      skirt_right_mid: 32,
      skirt_right_in: 33,
      leg_right_out: 34,
      leg_right_in: 35,
      shoes_right_bottom: 36,
      shoes_right_ankle: 37,
      shoes_right_front: 38,
      skirt_bottom_top_back: 39,
    },
    LEDPARTS: {
      mask_LED: { id: 0, len: 28 },
      glove_left_LED: { id: 1, len: 36 },
      glove_right_LED: { id: 2, len: 36 },
      shoes_left_LED: { id: 3, len: 30 },
      shoes_right_LED: { id: 4, len: 30 },
      hat_ring_LED: { id: 5, len: 54 },
      hat_main_LED: { id: 6, len: 100 },
    },
    LEDPARTS_MERGE: {},
  },
  vampire: {
    fps: 30,
    OFPARTS: {
      cloak_collar: 0,
      cloak_left_out: 1,
      arm_left_out: 2,
      arm_left_in: 3,
      shirt_left_out: 4,
      shirt_left_in: 5,
      waist_left: 6,
      arm_cuff_left: 7,
      hat_bottom_out: 8,
      hat_bottom_in: 9,
      cloak_right_out: 10,
      cloak_bottom_left: 11,
      arm_right_out: 12,
      arm_right_in: 13,
      shirt_right_out: 14,
      shirt_right_in: 15,
      waist_right: 16,
      arm_cuff_right: 17,
      hat_top: 18,
      cloak_bottom_right: 19,
      pants_top: 20,
      leg_left_out: 21,
      leg_left_spiral1: 22,
      leg_left_spiral2: 23,
      leg_left_in: 24,
      shoes_left_top: 25,
      shoes_left_bottom: 26,
      leg_right_out: 30,
      leg_right_spiral1: 31,
      leg_right_spiral2: 32,
      leg_right_in: 33,
      shoes_right_top: 35,
      shoes_right_bottom: 36,
    },
    LEDPARTS: {
      mask_LED: { id: 0, len: 28 },
      glove_left_LED: { id: 1, len: 36 },
      glove_right_LED: { id: 2, len: 36 },
    },
    LEDPARTS_MERGE: {},    
  },
  ghost_king: {
    fps: 30,
    OFPARTS: {
      cloak_collar: 0,
      cloak_left_out: 1,
      arm_left_out: 2,
      arm_left_in: 3,
      shirt_left_out: 4,
      shirt_left_in: 5,
      waist_left: 6,
      arm_cuff_left: 7,
      hat_bottom_out: 8,
      hat_bottom_in: 9,
      cloak_right_out: 10,
      cloak_bottom_left: 11,
      arm_right_out: 12,
      arm_right_in: 13,
      shirt_right_out: 14,
      shirt_right_in: 15,
      waist_right: 16,
      arm_cuff_right: 17,
      hat_top: 18,
      cloak_bottom_right: 19,
      leg_left_out: 21,
      leg_left_spiral1: 22,
      leg_left_spiral2: 23,
      leg_left_in: 24,
      shoes_left_top: 25,
      shoes_left_bottom: 26,
      leg_right_out: 30,
      leg_right_spiral1: 31,
      leg_right_spiral2: 32,
      leg_right_in: 33,
      shoes_right_top: 35,
      shoes_right_bottom: 36,
      belt_bottom: 38,
      belt_top: 39,
    },
    LEDPARTS: {
      mask_LED: { id: 0, len: 28 },
      glove_left_LED: { id: 1, len: 36 },
      glove_right_LED: { id: 2, len: 36 },
      crown_LED: { id: 3, len: 70 },
      cloak_back_LED: { id: 4, len: 36 },
      belt_LED: { id: 5, len: 15 },
    },
    LEDPARTS_MERGE: {},
  },
};
