import { ModelPinMapTable } from "@/schema/PinMapTable";

// The pinmap template for each model
export const characterPinMapTable: ModelPinMapTable = {
  bad_men: {
    fps: 30,
    OFPARTS: {
      right_muscle: 0,
      outer_right_back_arm: 1,
      outer_right_front_arm: 2,
      inner_right_arm: 3,
      right_weist: 4,
      outer_right_collar: 5,
      right_zipper: 6,
      inner_right_collar: 7,
      inner_left_collar: 8,
      claw: 9,
      mask: 10,
      shoulder: 11,
      left_muscle: 12,
      outer_left_back_arm: 13,
      outer_left_front_arm: 14,
      inner_left_arm: 15,
      left_weist: 16,
      outer_left_collar: 17,
      left_zipper: 18,
      bottom_clothes: 19,
      inner_right_shorts: 20,
      inner_right_pants: 21,
      right_shorts_bottom: 22,
      outer_right_shorts: 23,
      outer_right_pants_top: 24,
      outer_right_pants_bottom: 25,
      pants_top: 26,
      inner_left_shorts: 30,
      inner_left_pants: 31,
      left_shorts_bottom: 32,
      outer_left_shorts: 33,
      outer_left_pants_top: 34,
      outer_left_pants_bottom: 35,
    },
    LEDPARTS: {
      left_hand_LED: { id: 1, len: 32 },
      right_hand_LED: { id: 6, len: 32 },
      left_feet_LED: { id: 2, len: 41 },
      right_feet_LED: { id: 5, len: 41 },
      mask_LED: { id: 0, len: 18 },
      necktie_LED: { id: 7, len: 78 },
    },
    LEDPARTS_MERGE: {},
  },
  boss: {
    fps: 30,
    OFPARTS: {
      inner_right_weist: 0,
      inner_left_weist: 1,
      outer_right_arm: 2,
      inner_right_arm: 3,
      inner_right_cuff: 4,
      outer_right_cuff: 5,
      outer_right_weist: 6,
      bottom_right_weist: 7,
      belt: 8,
      middle_belt: 9,
      top_hat: 10,
      bottom_hat: 11,
      mask: 12,
      scarf: 13,
      outer_left_arm: 14,
      inner_left_arm: 15,
      inner_left_cuff: 16,
      outer_left_cuff: 17,
      outer_left_weist: 18,
      bottom_left_weist: 19,
      outer_right_pants: 20,
      inner_right_pants: 21,
      right_cape: 22,
      bottom_cape: 23,
      outer_left_pants: 30,
      inner_left_pants: 31,
      left_cape: 32,
    },
    LEDPARTS: {
      left_hand_LED: { id: 1, len: 32 },
      right_hand_LED: { id: 6, len: 32 },
      left_feet_LED: { id: 2, len: 56 },
      right_feet_LED: { id: 5, len: 56 },
    },
    LEDPARTS_MERGE: {},
  },
  main_character: {
    fps: 30,
    OFPARTS: {
      collar: 0,
      right_shoulder: 1,
      outer_right_arm: 2,
      right_cuff: 3,
      inner_right_arm: 4,
      outer_right_weist: 5,
      right_neckline: 6,
      inner_right_weist: 7,
      right_knot: 8,
      left_knot: 9,
      outer_hat: 10,
      inner_hat: 11,
      top_hat: 12,
      left_shoulder: 13,
      outer_left_arm: 14,
      left_cuff: 15,
      inner_left_arm: 16,
      outer_left_weist: 17,
      left_neckline: 18,
      inner_left_weist: 19,
      right_skirt: 20,
      outer_right_pants: 21,
      inner_right_pants: 22,
      inner_right_thin_cloth: 23,
      outer_right_thin_cloth: 24,
      bottom_thin_cloth: 25,
      left_skirt: 30,
      bottom_skirt: 31,
      outer_left_pants: 32,
      inner_left_pants: 33,
      inner_left_thin_cloth: 34,
      outer_left_thin_cloth: 35,
    },
    LEDPARTS: {
      left_hand_LED: { id: 1, len: 32 },
      right_hand_LED: { id: 6, len: 32 },
      left_feet_LED: { id: 2, len: 132 },
      right_feet_LED: { id: 5, len: 132 },
      mask_LED: { id: 0, len: 13 },
      star_LED: { id: 7, len: 1 },
    },
    LEDPARTS_MERGE: {},
  },
  good_men: {
    fps: 30,
    OFPARTS: {
      collar: 0,
      right_shoulder: 1,
      outer_right_arm: 2,
      outer_right_cuff: 3,
      inner_right_cuff: 4,
      inner_right_arm: 5,
      outer_right_weist: 6,
      inner_right_weist: 7,
      outer_hat: 10,
      inner_hat: 11,
      top_hat: 12,
      left_shoulder: 13,
      outer_left_arm: 14,
      outer_left_cuff: 15,
      inner_left_cuff: 16,
      inner_left_arm: 17,
      outer_left_weist: 18,
      inner_left_weist: 19,
      right_skirt: 20,
      bottom_skirt: 21,
      outer_right_pants: 22,
      inner_right_pants: 23,
      upper_right_knee: 24,
      lower_right_knee_down: 25,
      left_skirt: 30,
      outer_left_pants: 31,
      inner_left_pants: 32,
      upper_left_knee: 33,
      lower_left_knee: 34,
      middle_v: 35,
    },
    LEDPARTS: {
      left_hand_LED: { id: 1, len: 32 },
      right_hand_LED: { id: 6, len: 32 },
      left_feet_LED: { id: 2, len: 82 },
      right_feet_LED: { id: 5, len: 82 },
      mask_LED: { id: 0, len: 13 },
      star: { id: 7, len: 1 },
    },
    LEDPARTS_MERGE: {},
  },
};
