import { PinMapTable, PinMapTableSchema } from "@/schema/PinMapTable";

// Record the pinmap for every dancer
const pinMapTable: PinMapTable = {
  "0_hjko": {
    // yck
    dancer: "0_hjko",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      wrist_right: 5,
      belt_up_down: 7,
      belt_left_right: 8,
      body_bottom: 9,
      hat_outer: 10,
      hat_inner: 11,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      wrist_left: 18,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_outer_left: 30,
      leg_inner_left: 31,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 73 },
      shoe_right_LED: { id: 3, len: 73 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "1_sauby": {
    // arthur
    dancer: "1_sauby",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 81 },
      shoe_right_LED: { id: 3, len: 81 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "2_adam": {
    // ricky
    dancer: "2_adam",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 72 },
      shoe_right_LED: { id: 3, len: 72 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
};

PinMapTableSchema.parse(pinMapTable);

export default pinMapTable;
