import { PinMapTable, PinMapTableSchema } from "@/schema/PinMapTable";

// Record the pinmap for every dancer
const pinMapTable: PinMapTable = {
  "1_hank": {
    fps: 30,
    OFPARTS: {
      lapel_right: 4,
      lapel_left: 14,
      arm_outer_right: 9,
      arm_outer_left: 16,
      waist_right: 22,
      arm_inner_right: 8,
      waist_left: 26,
      arm_inner_left: 2,
      pocket: 0,
      hem: 24,
      collar_right: 11,
      collar_left: 15,
      collar_back: 13,
      brim: 12,
      beret: 17,
      leg_inner_right: 33,
      leg_inner_left: 30,
      leg_outer_right: 21,
      leg_outer_left: 27,
      leg_front_right: 32,
      leg_front_left: 31,
      leg_back_right: 34,
      leg_back_left: 29,
      arm_decor_right: 6,
      waist_decor_right: 23,
      arm_decor_left: 18,
      waist_decor_left: 25,
      zipper_inner_right: 7,
      zipper_outer_right: 5,
      zipper_inner_left: 3,
      zipper_outer_left: 1,
      tongue: 10,
      dome: 19,
    },
    LEDPARTS: {
      glove_right_LED: { id: 0, len: 42 },
      glove_left_LED: { id: 1, len: 42 },
      glasses_LED: { id: 2, len: 25 },
      buttons_LED: { id: 3, len: 2 },
      tie_LED: { id: 4, len: 73 },
      oxford_right_LED: { id: 5, len: 77 },
      oxford_left_LED: { id: 6, len: 77 },
    },
  },
  "2_henning": {
    fps: 30,
    OFPARTS: {
      lapel_right: 4,
      lapel_left: 14,
      arm_outer_right: 9,
      arm_outer_left: 16,
      waist_right: 5,
      arm_inner_right: 8,
      waist_left: 1,
      arm_inner_left: 19,
      pocket: 0,
      hem: 3,
      collar_right: 11,
      collar_left: 15,
      collar_back: 13,
      brim: 12,
      beret: 17,
      leg_inner_right: 33,
      leg_inner_left: 30,
      leg_outer_right: 21,
      leg_outer_left: 27,
      leg_front_right: 32,
      leg_front_left: 31,
      leg_back_right: 34,
      leg_back_left: 29,
    },
    LEDPARTS: {
      glove_right_LED: { id: 0, len: 42 },
      glove_left_LED: { id: 1, len: 42 },
      glasses_LED: { id: 2, len: 25 },
      buttons_LED: { id: 3, len: 2 },
      tie_LED: { id: 4, len: 73 },
      oxford_right_LED: { id: 5, len: 77 },
      oxford_left_LED: { id: 6, len: 77 },
    },
  },
  "3_hans": {
    fps: 30,
    OFPARTS: {
      lapel_right: 4,
      lapel_left: 14,
      arm_outer_right: 9,
      arm_outer_left: 16,
      waist_right: 5,
      arm_inner_right: 8,
      waist_left: 1,
      arm_inner_left: 19,
      pocket: 0,
      hem: 3,
      collar_right: 11,
      collar_left: 15,
      collar_back: 13,
      brim: 12,
      beret: 17,
      leg_inner_right: 33,
      leg_inner_left: 30,
      leg_outer_right: 21,
      leg_outer_left: 27,
      leg_front_right: 32,
      leg_front_left: 31,
      leg_back_right: 34,
      leg_back_left: 29,
    },
    LEDPARTS: {
      glove_right_LED: { id: 0, len: 42 },
      glove_left_LED: { id: 1, len: 42 },
      glasses_LED: { id: 2, len: 25 },
      buttons_LED: { id: 3, len: 2 },
      tie_LED: { id: 4, len: 73 },
      oxford_right_LED: { id: 5, len: 77 },
      oxford_left_LED: { id: 6, len: 77 },
    },
  },
  "4_rayh": {
    fps: 30,
    OFPARTS: {
      lapel_right: 4,
      lapel_left: 14,
      arm_outer_right: 9,
      arm_outer_left: 16,
      waist_right: 5,
      arm_inner_right: 8,
      waist_left: 1,
      arm_inner_left: 19,
      pocket: 0,
      hem: 3,
      collar_right: 11,
      collar_left: 15,
      collar_back: 13,
      brim: 12,
      beret: 17,
      leg_inner_right: 33,
      leg_inner_left: 30,
      leg_outer_right: 21,
      leg_outer_left: 27,
      leg_front_right: 32,
      leg_front_left: 31,
      leg_back_right: 34,
      leg_back_left: 29,
    },
    LEDPARTS: {
      glove_right_LED: { id: 0, len: 42 },
      glove_left_LED: { id: 1, len: 42 },
      glasses_LED: { id: 2, len: 25 },
      buttons_LED: { id: 3, len: 2 },
      tie_LED: { id: 4, len: 73 },
      oxford_right_LED: { id: 5, len: 77 },
      oxford_left_LED: { id: 6, len: 77 },
    },
  },
  "5_justin": {
    fps: 30,
    OFPARTS: {
      lapel_right: 4,
      lapel_left: 14,
      arm_outer_right: 9,
      arm_outer_left: 16,
      waist_right: 5,
      arm_inner_right: 8,
      waist_left: 1,
      arm_inner_left: 19,
      pocket: 0,
      hem: 3,
      collar_right: 11,
      collar_left: 15,
      collar_back: 13,
      brim: 12,
      beret: 17,
      leg_inner_right: 33,
      leg_inner_left: 30,
      leg_outer_right: 21,
      leg_outer_left: 27,
      leg_front_right: 32,
      leg_front_left: 31,
      leg_back_right: 34,
      leg_back_left: 29,
    },
    LEDPARTS: {
      glove_right_LED: { id: 0, len: 42 },
      glove_left_LED: { id: 1, len: 42 },
      glasses_LED: { id: 2, len: 25 },
      buttons_LED: { id: 3, len: 2 },
      tie_LED: { id: 4, len: 73 },
      oxford_right_LED: { id: 5, len: 77 },
      oxford_left_LED: { id: 6, len: 77 },
    },
  },
  "6_stantheman": {
    fps: 30,
    OFPARTS: {
      shoulder_left: 16,
      shoulder_right: 12,
      chest_left: 19,
      chest_right: 9,
      arm_left: 18,
      arm_right: 10,
      lymphatic_duct_left: 17,
      lymphatic_duct_right: 14,
      oblique_left: 2,
      oblique_right: 8,
      belt_top: 7,
      belt_bottom: 3,
      core: 0,
      belt_left: 1,
      belt_right: 6,
      mohawk: 13,
      tadpole_left: 15,
      tadpole_right: 11,
      cross_left: 29,
      cross_right: 34,
      dot_left: 30,
      dot_right: 33,
      shoelace_left: 31,
      shoelace_right: 32,
      kidney_left: 25,
      cape_left: 27,
      cape_bottom: 20,
      kidney_right: 24,
      cape_right: 21,
    },
    LEDPARTS: {
      wrist_left_LED: { id: 0, len: 50 },
      wrist_right_LED: { id: 1, len: 50 },
      foot_left_LED: { id: 2, len: 50 },
      foot_right_LED: { id: 3, len: 50 },
      fingers_left_LED: { id: 4, len: 28 },
      fingers_right_LED: { id: 5, len: 28 },
      kunai_LED: { id: 6, len: 0 },
      mask_LED: { id: 7, len: 60 },
    },
  },
  "7_ken": {
    fps: 30,
    OFPARTS: {
      shoulder_left: 16,
      shoulder_right: 12,
      chest_left: 19,
      chest_right: 9,
      arm_left: 18,
      arm_right: 10,
      lymphatic_duct_left: 17,
      lymphatic_duct_right: 14,
      oblique_left: 2,
      oblique_right: 8,
      belt_top: 7,
      belt_bottom: 3,
      core: 0,
      belt_left: 1,
      belt_right: 6,
      mohawk: 13,
      tadpole_left: 15,
      tadpole_right: 11,
      cross_left: 29,
      cross_right: 34,
      dot_left: 30,
      dot_right: 33,
      shoelace_left: 31,
      shoelace_right: 32,
    },
    LEDPARTS: {
      wrist_left_LED: { id: 0, len: 50 },
      wrist_right_LED: { id: 1, len: 50 },
      foot_left_LED: { id: 2, len: 50 },
      foot_right_LED: { id: 3, len: 50 },
      fingers_left_LED: { id: 4, len: 28 },
      fingers_right_LED: { id: 5, len: 28 },
      kunai_LED: { id: 6, len: 0 },
      mask_LED: { id: 7, len: 60 },
    },
  },
  "8_samuel": {
    fps: 30,
    OFPARTS: {
      shoulder_left: 16,
      shoulder_right: 12,
      chest_left: 19,
      chest_right: 9,
      arm_left: 18,
      arm_right: 10,
      lymphatic_duct_left: 17,
      lymphatic_duct_right: 14,
      oblique_left: 2,
      oblique_right: 8,
      belt_top: 7,
      belt_bottom: 3,
      core: 0,
      belt_left: 1,
      belt_right: 6,
      mohawk: 13,
      tadpole_left: 15,
      tadpole_right: 11,
      cross_left: 29,
      cross_right: 34,
      dot_left: 30,
      dot_right: 33,
      shoelace_left: 31,
      shoelace_right: 32,
    },
    LEDPARTS: {
      wrist_left_LED: { id: 0, len: 50 },
      wrist_right_LED: { id: 1, len: 50 },
      foot_left_LED: { id: 2, len: 50 },
      foot_right_LED: { id: 3, len: 50 },
      fingers_left_LED: { id: 4, len: 28 },
      fingers_right_LED: { id: 5, len: 28 },
      kunai_LED: { id: 6, len: 0 },
      mask_LED: { id: 7, len: 60 },
    },
  },
};

PinMapTableSchema.parse(pinMapTable);

export default pinMapTable;
