import { PinMapTable, PinMapTableSchema } from "@/schema/PinMapTable";

// Record the pinmap for every dancer
const pinMapTable: PinMapTable = {
  "0_xn": {
    dancer: "0_xn",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      wrist_right: 5,
      belt_up_down: 7,
      belt_left_right: 8,
      body_bottom: 9,
      hat_outer: 10,
      hat_inner: 11,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      wrist_left: 18,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_outer_left: 30,
      leg_inner_left: 31,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 75 },
      shoe_right_LED: { id: 3, len: 75 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "1_yck": {
    dancer: "1_yck",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      wrist_right: 5,
      belt_up_down: 7,
      belt_left_right: 8,
      body_bottom: 9,
      hat_outer: 10,
      hat_inner: 11,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      wrist_left: 18,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_outer_left: 30,
      leg_inner_left: 31,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 73 },
      shoe_right_LED: { id: 3, len: 73 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "2_sssam": {
    dancer: "2_sssam",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_top: 10,
      hat_side: 11,
      hat_bottom: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 76 },
      shoe_right_LED: { id: 3, len: 76 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "3_crc": {
    dancer: "3_crc",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 72 },
      shoe_right_LED: { id: 3, len: 72 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "4_arthur": {
    dancer: "4_arthur",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 81 },
      shoe_right_LED: { id: 3, len: 81 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "5_cs": {
    dancer: "5_cs",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 68 },
      shoe_right_LED: { id: 3, len: 68 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "6_rakec": {
    dancer: "6_rakec",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 69 },
      shoe_right_LED: { id: 3, len: 69 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "7_jya": {
    dancer: "7_jya",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 68 },
      shoe_right_LED: { id: 3, len: 68 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "8_circle": {
    dancer: "8_circle",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 68 },
      shoe_right_LED: { id: 3, len: 68 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "9_ricky": {
    dancer: "9_ricky",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 72 },
      shoe_right_LED: { id: 3, len: 72 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "10_chris": {
    dancer: "10_chris",
    fps: 30,
    OFPARTS: {
      body_inner_right: 0,
      body_outer_right: 1,
      collar_short: 2,
      shoulder_right: 3,
      arm_inner_right: 4,
      elbow_right: 5,
      arm_front_right: 6,
      body_bottom: 7,
      belt: 8,
      hat_180: 10,
      hat_135: 11,
      hat_90: 12,
      body_inner_left: 13,
      body_outer_left: 14,
      collar_long: 15,
      shoulder_left: 16,
      arm_inner_left: 17,
      elbow_left: 18,
      arm_front_left: 19,
      leg_outer_right: 20,
      leg_inner_right: 21,
      leg_bottom_right: 22,
      sock_right: 23,
      leg_outer_left: 30,
      leg_inner_left: 31,
      leg_bottom_left: 32,
      sock_left: 33,
    },
    LEDPARTS: {
      shoe_left_LED: { id: 0, len: 75 },
      shoe_right_LED: { id: 3, len: 75 },
      face_LED: { id: 5, len: 14 },
      glove_left_LED: { id: 7, len: 36 },
      glove_right_LED: { id: 4, len: 36 },
    },
    LEDPARTS_MERGE: {
      shoe_left_LED: [
        "shoe_bottom_left_LED",
        "shoe_outer_left_LED",
        "shoe_top_left_LED",
        "shoe_front_left_LED",
      ],
      shoe_right_LED: [
        "shoe_bottom_right_LED",
        "shoe_outer_right_LED",
        "shoe_top_right_LED",
        "shoe_front_right_LED",
      ],
    },
  },
  "11_temple_1": {
    dancer: "11_temple",
    fps: 30,
    OFPARTS: {
      lamp: 0,
      vine_tiles: 1,
      roof_ridge_left: 2,
      roof_ridge_right: 3,
      roof_ridge_top1: 4,
      roof_ridge_top2: 5,
      vine_pillar_left: 10,
      vine_pillar_right: 11,
      vine_base: 12,
      base1: 13,
      base2: 14,
    },
    LEDPARTS: {
      roof_tile1_LED: { id: 0, len: 60 },
      roof_tile2_LED: { id: 1, len: 63 },
      pillar_left_LED: { id: 2, len: 24 },
      lamp_left_LED: { id: 3, len: 3 },
      lamp_right_LED: { id: 4, len: 3 },
      pillar_right_LED: { id: 5, len: 24 },
      pillar_roof_deco_LED: { id: 6, len: 60 },
      roof_tile3_LED: { id: 7, len: 84 },
    },
    LEDPARTS_MERGE: {},
  },
  "12_temple_2": {
    dancer: "11_temple",
    fps: 30,
    OFPARTS: {
      face: 0,
      arm_left: 1,
      arm_right: 2,
      leg_left: 3,
      leg_right: 4,
      detail_left: 5,
      detail_right: 6,
    },
    LEDPARTS: {
      left_side_LED: { id: 2, len: 30 },
      face_LED: { id: 3, len: 15 },
      center_LED: { id: 4, len: 60 },
      right_side_LED: { id: 5, len: 30 },
    },
    LEDPARTS_MERGE: {},
  },
  "13_bridge_1": {
    dancer: "12_bridge",
    fps: 30,
    OFPARTS: {
      front_right_down_1: 0,
      front_right_down_2: 1,
      front_right_4: 2,
      front_right_3: 3,
      front_right_2: 4,
      front_right_1: 5,
      front_right_top_2: 10,
      front_right_top_1: 11,
      front_right_middle_1: 12,
      front_right_middle_2: 13,
      front_right_middle_3: 14,
      front_left_down_1: 20,
      front_left_down_2: 21,
      front_left_4: 22,
      front_left_3: 23,
      front_left_2: 24,
      front_left_1: 25,
      front_left_top_1: 30,
      front_left_top_2: 31,
      front_left_middle_1: 32,
      front_left_middle_2: 33,
      front_left_middle_3: 34,
    },
    LEDPARTS: {
      fire2_LED: { id: 3, len: 20 },
      lamp_front_right_LED: { id: 4, len: 33 },
      fire1_LED: { id: 6, len: 72 },
      lamp_front_left_LED: { id: 7, len: 33 },
    },
    LEDPARTS_MERGE: {},
  },
  "15_nian_1": {
    dancer: "13_nian",
    fps: 30,
    OFPARTS: {
      backfoot_right_out: 0,
      backfoot_right_in: 1,
      backpalm_right_out: 2,
      backpalm_right_mid: 3,
      backpalm_right_in: 4,
      backfoot_left_out: 9,
      backpalm_left_out: 10,
      backpalm_left_mid: 11,
      forefoot_left_out: 20,
      forefoot_left_mid: 21,
      forefoot_left_in: 22,
      forepalm_left_out: 23,
      forepalm_left_in: 24,
      tail1: 30,
      tail2: 31,
      tail3: 32,
      tail4: 33,
      back: 34,
      belly: 35,
    },
    LEDPARTS: {
      backfoot_right_LED: { id: 0, len: 57 },
      backfoot_left_LED: { id: 3, len: 30 },
      tail_LED: { id: 5, len: 78 },
      slash_LED: { id: 6, len: 40 },
    },
    LEDPARTS_MERGE: {},
  },
  "16_nian_2": {
    dancer: "13_nian",
    fps: 30,
    OFPARTS: {
      forefoot_right_out: 0,
      forefoot_right_mid:1,
      forefoot_right_in: 2,
      forepalm_right_out: 3,
      forepalm_right_in: 4,
      hair_up: 10,
      hair_rightup: 11,
      hair_leftup: 12,
      hair_rightbottom: 13,
      hair_leftbottom: 14,
      face_up: 15,
      face_right: 16,
      face_left: 17,
      eye_right: 20,
      eye_left: 21,
      nose: 22, 
      jaw_up: 23,
      jaw_mid: 24,
      jaw_low: 25
    },
    LEDPARTS: {
      forefoot_left_LED: { id: 0, len: 30 },
      forefoot_right_LED: { id: 3, len: 40 },
      back_LED: { id: 4, len: 60 },
      upperjaw_LED: { id: 5, len: 36 },
      lowerjaw_LED: { id: 6, len: 12 }
    },
    LEDPARTS_MERGE: {},
  },
  "17_sword": {
    dancer: "14_sword",
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      fan_left_LED: { id: 1, len: 31 },
      sword_LED: { id: 2, len: 131 },
      fan_right_LED: { id: 3, len: 31 },
    },
    LEDPARTS_MERGE: {},
  },
  "18_guandao": {
    dancer: "15_guandao",
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      shaft_short_LED: { id: 1, len: 34 },
      shaft_long_LED: { id: 2, len: 47 },
      blade_holder_LED: { id: 3, len: 34 },
      blade_LED: { id: 4, len: 76 },
      effect_LED: { id: 5, len: 91 },
    },
    LEDPARTS_MERGE: {},
  },
  "19_effectboard": {
    dancer: "16_effectboard",
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      LED: { id: 1, len: 128 },
    },
    LEDPARTS_MERGE: {},
  },
};

PinMapTableSchema.parse(pinMapTable);

export default pinMapTable;
