import { ModelPinMapTable } from "@/schema/PinMapTable";

export const PropPinMapTable: ModelPinMapTable = {
  coffin: {
    fps: 30,
    OFPARTS: {
      outline_BRU: 0,
      outline_BRD: 1,
      outline_BLU: 2,
      outline_BLD: 3,
      outline_BT: 4,
      outline_BB: 5,
    },
    LEDPARTS: {
      frontL_LED: { id: 0, len: 60 },
      frontR_LED: { id: 1, len: 60 },
      left_LED: { id: 2, len: 70 },
      right_LED: { id: 3, len: 70 },
      cross_LED: { id: 4, len: 100 },
      outline_DU_LED: { id: 5, len: 33 },
      outline_DD_LED: { id: 6, len: 27 },
    },
    LEDPARTS_MERGE: {},
  },
  cross: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      wingleft_LED: { id: 0, len: 76 },
      wingright_LED: { id: 1, len: 76 },
      top_LED: { id: 2, len: 99 },
      centerpiece_LED: { id: 3, len: 104 },
      baseleft_LED: { id: 4, len: 58 },
      baseright_LED: { id: 5, len: 58 },
    },
    LEDPARTS_MERGE: {},
  },
  altar1_bottom: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      front_LED: { id: 0, len: 80 },
      side_LED: { id: 1, len: 80 },
      frontdecor_LED: { id: 2, len: 46 },
      sidedecor_LED: { id: 3, len: 46 },
      edge_LED: { id: 4, len: 40 },
      pillar_right_LED: { id: 5, len: 54 },
      pillar_left_LED: { id: 6, len: 54 },
    },
    LEDPARTS_MERGE: {},
  },
  altar1_top: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      fire_left_LED: { id: 0, len: 62 },
      fire_right_LED: { id: 1, len: 62 },
      chain1_LED: { id: 2, len: 75 },
      chain2_LED: { id: 3, len: 75 },
      fire_front1_LED: { id: 4, len: 46 },
      fire_front2_LED: { id: 5, len: 46 },
    },
    LEDPARTS_MERGE: {},
  },
  altar2_bottom: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      front_LED: { id: 0, len: 80 },
      side_LED: { id: 1, len: 80 },
      frontdecor_LED: { id: 2, len: 46 },
      sidedecor_LED: { id: 3, len: 46 },
      edge_LED: { id: 4, len: 40 },
      pillar_right_LED: { id: 5, len: 54 },
      pillar_left_LED: { id: 6, len: 54 },
    },
    LEDPARTS_MERGE: {},
  },
  altar2_top: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      fire_left_LED: { id: 0, len: 62 },
      fire_right_LED: { id: 1, len: 62 },
      chain1_LED: { id: 2, len: 75 },
      chain2_LED: { id: 3, len: 75 },
      fire_front1_LED: { id: 4, len: 46 },
      fire_front2_LED: { id: 5, len: 46 },
    },
    LEDPARTS_MERGE: {},
  },
  gem: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      intact_LED: { id: 0, len: 30 },
      broken_LED: { id: 1, len: 30 },
    },
    LEDPARTS_MERGE: {},
  },
  pole: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      out_left_LED: { id: 0, len: 53 },
      out_right_LED: { id: 1, len: 53 },
      in_midright_LED: { id: 2, len: 53 },
      in_midleft_LED: { id: 3, len: 53 },
      in_right_LED: { id: 4, len: 53 },
      in_left_LED: { id: 5, len: 53 },
      top_LED: { id: 6, len: 50 },
      side_LED: { id: 7, len: 38 },
    },
    LEDPARTS_MERGE: {},
  },
  balcony: {
    fps: 30,
    OFPARTS: {
      bottom: 0,
      mid_horizontal: 1,
      mid_vertical_right: 2,
      mid_vertical_left: 3,
      top_right_left: 4,
      top_right_right: 5,
      top_left_right: 6,
      top_left_left: 7,
      roof_horizontal: 8,
      roof_top: 9,
    },
    LEDPARTS: {
      bottom_right_LED: { id: 0, len: 36 },
      bottom_left_LED: { id: 1, len: 36 },
      mid_right_LED: { id: 2, len: 36 },
      mid_mid_LED: { id: 3, len: 48 },
      mid_left_LED: { id: 4, len: 36 },
      top_right_LED: { id: 5, len: 43 },
      top_left_LED: { id: 6, len: 43 },
      window_LED: { id: 7, len: 72 },
    },
    LEDPARTS_MERGE: {},
  },
  fireplace: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      left_LED: { id: 0, len: 76 },
      middleright_LED: { id: 1, len: 90 },
      face_LED: { id: 3, len: 12 },
      middleleft_LED: { id: 4, len: 80 },
      right_LED: { id: 5, len: 78 },
      head_LED: { id: 6, len: 51 },
    },
    LEDPARTS_MERGE: {},    
  },
  gun: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      left_logo_LED: { id: 0, len: 30 },
      left_trigger_LED: { id: 1, len: 36 },
      left_barrel_LED: { id: 2, len: 36 },
      right_logo_LED: { id: 3, len: 30 },
      right_trigger_LED: { id: 4, len: 36 },
      right_barrel_LED: { id: 5, len: 36 },
      acrylic_LED: { id: 6, len: 3 },
    },
    LEDPARTS_MERGE: {},   
  },
  axe: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      main_LED: { id: 1, len: 88 },
    },
    LEDPARTS_MERGE: {}, 
  },
  staff: {
    fps: 30,
    OFPARTS: {},
    LEDPARTS: {
      skeleton_LED: { id: 0, len: 16 },
      stick_LED: { id: 1, len: 60 },
      snake_LED: { id: 2, len: 50 },
      eyes_LED: { id: 3, len: 6 },
    },
    LEDPARTS_MERGE: {},
  },
};