BT_SENDER_PORT = "/dev/tty.usbserial-0001"

MUSIC_FILE_PATH = "../files/music/0317.wav"

DANCER_LIST = [
    ("all", "none"),
    ("0_liao", "ghost_king"),
    ("1_lin", "ghost_king"),
    ("2_feng", "main_girl"),
    ("3_chen", "main_girl"),
    ("4_roy", "vampire"),
    ("5_chiu", "vampire"),
    ("6_su", "main_boy"),
    ("7_li", "main_boy"),
    ("8_hsieh", "hunter"),
    ("9_yang", "hunter"),
    ("10_tsai", "hunter"),
    ("11_luo", "hunter"),
    ("12_coffin", "coffin"),
    ("13_altar_top1", "altar1_top"),
    ("14_altar_bottom1", "altar1_bottom"),
    ("15_altar_top2", "altar2_top"),
    ("16_altar_bottom2", "altar2_bottom"),
    ("17_cross", "cross"),
    ("18_gem", "gem"),
    ("19_pole", "pole"),
    ("20_fireplace", "fireplace"),
    ("21_axe1", "axe"),
    ("22_axe2", "axe"),
    ("23_balcony", "balcony"),
    ("24_gun", "gun"),
    ("25_staff1", "staff"),
    ("26_staff2", "staff"),
]

MODEL_PIN_MAP_TABLE = {
    "hunter": {
        "fps": 30,
        "OFPARTS": {
            "collar": 0,
            "shirt_left_in": 1,
            "shirt_left_out": 2,
            "arm_left_out": 3,
            "arm_left_in": 4,
            "cloak_hat_top": 7,
            "cloak_hat_edge": 8,
            "belt_out": 9,
            "cloak_collar_button": 10,
            "shirt_right_in": 11,
            "shirt_right_out": 12,
            "arm_right_out": 13,
            "arm_right_in": 14,
            "shirt_button_top": 16,
            "shirt_button_mid": 17,
            "shirt_button_bottom": 18,
            "belt_in": 19,
            "leg_left_in": 20,
            "leg_left_out": 21,
            "cloak_left_out": 22,
            "cloak_left_in": 23,
            "cloak_bottom_left_out": 24,
            "cloak_bottom_left_in": 25,
            "shoes_left_top": 26,
            "shoes_left_bottom": 27,
            "leg_right_in": 30,
            "leg_right_out": 31,
            "cloak_right_out": 32,
            "cloak_right_in": 33,
            "cloak_bottom_right_out": 34,
            "cloak_bottom_right_in": 35,
            "shoes_right_top": 36,
            "shoes_right_bottom": 37,
        },
        "LEDPARTS": {
            "glove_left_LED": {"id": 1, "len": 36},
            "glove_right_LED": {"id": 2, "len": 36},
            "wrist_left_LED": {"id": 3, "len": 18},
            "wrist_right_LED": {"id": 4, "len": 18},
            "bearpalm_LED": {"id": 5, "len": 9},
        },
        "LEDPARTS_MERGE": {},
    },
    "main_boy": {
        "fps": 30,
        "OFPARTS": {
            "collar": 0,
            "shirt_left_in": 1,
            "shirt_left_out": 2,
            "arm_left_out": 3,
            "arm_left_in": 4,
            "cloak_hat_top": 7,
            "cloak_hat_edge": 8,
            "belt_out": 9,
            "cloak_collar_button": 10,
            "shirt_right_in": 11,
            "shirt_right_out": 12,
            "arm_right_out": 13,
            "arm_right_in": 14,
            "shirt_button_top": 16,
            "shirt_button_mid": 17,
            "shirt_button_bottom": 18,
            "belt_in": 19,
            "leg_left_in": 20,
            "leg_left_out": 21,
            "cloak_left_out": 22,
            "cloak_left_in": 23,
            "cloak_bottom_left_out": 24,
            "cloak_bottom_left_in": 25,
            "shoes_left_top": 26,
            "shoes_left_bottom": 27,
            "leg_right_in": 30,
            "leg_right_out": 31,
            "cloak_right_out": 32,
            "cloak_right_in": 33,
            "cloak_bottom_right_out": 34,
            "cloak_bottom_right_in": 35,
            "shoes_right_top": 36,
            "shoes_right_bottom": 37,
        },
        "LEDPARTS": {
            "mask_LED": {"id": 0, "len": 8},
            "glove_left_LED": {"id": 1, "len": 36},
            "glove_right_LED": {"id": 2, "len": 36},
            "bearpalm_LED": {"id": 3, "len": 9},
            "shoulder_left_LED": {"id": 4, "len": 12},
            "shoulder_right_LED": {"id": 5, "len": 12},
            "wrist_left_LED": {"id": 6, "len": 27},
            "wrist_right_LED": {"id": 7, "len": 18},
        },
        "LEDPARTS_MERGE": {},
    },
    "main_girl": {
        "fps": 30,
        "OFPARTS": {
            "cloak_out": 0,
            "cloak_arm_left": 1,
            "arm_left_out": 2,
            "arm_left_in": 3,
            "arm_cuff_left": 4,
            "shirt_left_out": 5,
            "shirt_left_mid": 6,
            "shirt_left_in": 7,
            "belt_left": 8,
            "cloak_left_in": 9,
            "cross": 10,
            "cloak_arm_right": 11,
            "arm_right_out": 12,
            "arm_right_in": 13,
            "arm_cuff_right": 14,
            "shirt_right_out": 15,
            "shirt_right_mid": 16,
            "shirt_right_in": 17,
            "belt_right": 18,
            "cloak_right_in": 19,
            "skirt_bottom_bottom_front": 20,
            "skirt_left_out": 21,
            "skirt_left_mid": 22,
            "skirt_left_in": 23,
            "leg_left_out": 24,
            "leg_left_in": 25,
            "shoes_left_bottom": 26,
            "shoes_left_ankle": 27,
            "shoes_left_front": 28,
            "skirt_bottom_bottom_back": 29,
            "skirt_bottom_top_front": 30,
            "skirt_right_out": 31,
            "skirt_right_mid": 32,
            "skirt_right_in": 33,
            "leg_right_out": 34,
            "leg_right_in": 35,
            "shoes_right_bottom": 36,
            "shoes_right_ankle": 37,
            "shoes_right_front": 38,
            "skirt_bottom_top_back": 39,
        },
        "LEDPARTS": {
            "mask_LED": {"id": 0, "len": 28},
            "glove_left_LED": {"id": 1, "len": 36},
            "glove_right_LED": {"id": 2, "len": 36},
            "shoes_left_LED": {"id": 3, "len": 30},
            "shoes_right_LED": {"id": 4, "len": 30},
            "hat_ring_LED": {"id": 5, "len": 54},
            "hat_main_LED": {"id": 6, "len": 100},
        },
        "LEDPARTS_MERGE": {},
    },
    "vampire": {
        "fps": 30,
        "OFPARTS": {
            "cloak_collar": 0,
            "cloak_left_out": 1,
            "arm_left_out": 2,
            "arm_left_in": 3,
            "shirt_left_out": 4,
            "shirt_left_in": 5,
            "waist_left": 6,
            "arm_cuff_left": 7,
            "hat_bottom_out": 8,
            "hat_bottom_in": 9,
            "cloak_right_out": 10,
            "cloak_bottom_left": 11,
            "arm_right_out": 12,
            "arm_right_in": 13,
            "shirt_right_out": 14,
            "shirt_right_in": 15,
            "waist_right": 16,
            "arm_cuff_right": 17,
            "hat_top": 18,
            "cloak_bottom_right": 19,
            "pants_top": 20,
            "leg_left_out": 21,
            "leg_left_spiral1": 22,
            "leg_left_spiral2": 23,
            "leg_left_in": 24,
            "shoes_left_top": 25,
            "shoes_left_bottom": 26,
            "leg_right_out": 30,
            "leg_right_spiral1": 31,
            "leg_right_spiral2": 32,
            "leg_right_in": 33,
            "shoes_right_top": 35,
            "shoes_right_bottom": 36,
        },
        "LEDPARTS": {
            "mask_LED": {"id": 0, "len": 28},
            "glove_left_LED": {"id": 1, "len": 36},
            "glove_right_LED": {"id": 2, "len": 36},
        },
        "LEDPARTS_MERGE": {},
    },
    "ghost_king": {
        "fps": 30,
        "OFPARTS": {
            "cloak_collar": 0,
            "cloak_left_out": 1,
            "arm_left_out": 2,
            "arm_left_in": 3,
            "shirt_left_out": 4,
            "shirt_left_in": 5,
            "waist_left": 6,
            "arm_cuff_left": 7,
            "hat_bottom_out": 8,
            "hat_bottom_in": 9,
            "cloak_right_out": 10,
            "cloak_bottom_left": 11,
            "arm_right_out": 12,
            "arm_right_in": 13,
            "shirt_right_out": 14,
            "shirt_right_in": 15,
            "waist_right": 16,
            "arm_cuff_right": 17,
            "hat_top": 18,
            "cloak_bottom_right": 19,
            "leg_left_out": 21,
            "leg_left_spiral1": 22,
            "leg_left_spiral2": 23,
            "leg_left_in": 24,
            "shoes_left_top": 25,
            "shoes_left_bottom": 26,
            "leg_right_out": 30,
            "leg_right_spiral1": 31,
            "leg_right_spiral2": 32,
            "leg_right_in": 33,
            "shoes_right_top": 35,
            "shoes_right_bottom": 36,
            "belt_bottom": 38,
            "belt_top": 39,
        },
        "LEDPARTS": {
            "mask_LED": {"id": 0, "len": 28},
            "glove_left_LED": {"id": 1, "len": 36},
            "glove_right_LED": {"id": 2, "len": 36},
            "crown_LED": {"id": 3, "len": 70},
            "cloak_back_LED": {"id": 4, "len": 36},
            "belt_LED": {"id": 5, "len": 15},
        },
        "LEDPARTS_MERGE": {},
    },
    "coffin": {
        "fps": 30,
        "OFPARTS": {
            "outline_BRU": 0,
            "outline_BRD": 1,
            "outline_BLU": 2,
            "outline_BLD": 3,
            "outline_BT": 4,
            "outline_BB": 5,
        },
        "LEDPARTS": {
            "frontL_LED": {"id": 0, "len": 60},
            "frontR_LED": {"id": 1, "len": 60},
            "left_LED": {"id": 2, "len": 70},
            "right_LED": {"id": 3, "len": 70},
            "cross_LED": {"id": 4, "len": 100},
            "outline_DU_LED": {"id": 5, "len": 33},
            "outline_DD_LED": {"id": 6, "len": 27},
        },
        "LEDPARTS_MERGE": {},
    },
    "cross": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "wingleft_LED": {"id": 0, "len": 76},
            "wingright_LED": {"id": 1, "len": 76},
            "top_LED": {"id": 2, "len": 99},
            "centerpiece_LED": {"id": 3, "len": 100},
            "baseleft_LED": {"id": 4, "len": 58},
            "baseright_LED": {"id": 5, "len": 58},
        },
        "LEDPARTS_MERGE": {},
    },
    "altar1_bottom": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "front_LED": {"id": 0, "len": 80},
            "side_LED": {"id": 1, "len": 80},
            "frontdecor_LED": {"id": 2, "len": 46},
            "sidedecor_LED": {"id": 3, "len": 46},
            "edge_LED": {"id": 4, "len": 40},
            "pillar_right_LED": {"id": 5, "len": 54},
            "pillar_left_LED": {"id": 6, "len": 54},
        },
        "LEDPARTS_MERGE": {},
    },
    "altar1_top": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "fire_left_LED": {"id": 0, "len": 62},
            "fire_right_LED": {"id": 1, "len": 62},
            "chain1_LED": {"id": 2, "len": 75},
            "chain2_LED": {"id": 3, "len": 75},
            "fire_front1_LED": {"id": 4, "len": 46},
            "fire_front2_LED": {"id": 5, "len": 46},
        },
        "LEDPARTS_MERGE": {},
    },
    "altar2_bottom": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "front_LED": {"id": 0, "len": 80},
            "side_LED": {"id": 1, "len": 80},
            "frontdecor_LED": {"id": 2, "len": 46},
            "sidedecor_LED": {"id": 3, "len": 46},
            "edge_LED": {"id": 4, "len": 40},
            "pillar_right_LED": {"id": 5, "len": 54},
            "pillar_left_LED": {"id": 6, "len": 54},
        },
        "LEDPARTS_MERGE": {},
    },
    "altar2_top": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "fire_left_LED": {"id": 0, "len": 62},
            "fire_right_LED": {"id": 1, "len": 62},
            "chain1_LED": {"id": 2, "len": 75},
            "chain2_LED": {"id": 3, "len": 75},
            "fire_front1_LED": {"id": 4, "len": 46},
            "fire_front2_LED": {"id": 5, "len": 46},
        },
        "LEDPARTS_MERGE": {},
    },
    "gem": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "intact_LED": {"id": 0, "len": 30},
            "broken_LED": {"id": 1, "len": 30},
        },
        "LEDPARTS_MERGE": {},
    },
    "pole": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "out_left_LED": {"id": 0, "len": 53},
            "out_right_LED": {"id": 1, "len": 53},
            "in_midright_LED": {"id": 2, "len": 53},
            "in_midleft_LED": {"id": 3, "len": 53},
            "in_right_LED": {"id": 4, "len": 53},
            "in_left_LED": {"id": 5, "len": 53},
            "top_LED": {"id": 6, "len": 50},
            "side_LED": {"id": 7, "len": 38},
        },
        "LEDPARTS_MERGE": {},
    },
    "balcony": {
        "fps": 30,
        "OFPARTS": {
            "bottom": 0,
            "mid_horizontal": 1,
            "mid_vertical_right": 2,
            "mid_vertical_left": 3,
            "top_right_left": 4,
            "top_right_right": 5,
            "top_left_right": 6,
            "top_left_left": 7,
            "roof_horizontal": 8,
            "roof_top": 9,
        },
        "LEDPARTS": {
            "bottom_right_LED": {"id": 0, "len": 36},
            "bottom_left_LED": {"id": 1, "len": 36},
            "mid_right_LED": {"id": 2, "len": 36},
            "mid_mid_LED": {"id": 3, "len": 48},
            "mid_left_LED": {"id": 4, "len": 36},
            "top_right_LED": {"id": 5, "len": 43},
            "top_left_LED": {"id": 6, "len": 43},
            "window_LED": {"id": 7, "len": 72},
        },
        "LEDPARTS_MERGE": {},
    },
    "fireplace": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "left_LED": {"id": 0, "len": 89},
            "middleright_LED": {"id": 1, "len": 89},
            "face_LED": {"id": 3, "len": 12},
            "middleleft_LED": {"id": 4, "len": 79},
            "right_LED": {"id": 5, "len": 90},
            "head_LED": {"id": 6, "len": 51},
        },
        "LEDPARTS_MERGE": {},
    },
    "gun": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "left_logo_LED": {"id": 0, "len": 30},
            "left_trigger_LED": {"id": 1, "len": 36},
            "left_barrel_LED": {"id": 2, "len": 36},
            "right_logo_LED": {"id": 3, "len": 30},
            "right_trigger_LED": {"id": 4, "len": 36},
            "right_barrel_LED": {"id": 5, "len": 36},
            "acrylic_LED": {"id": 6, "len": 3},
        },
        "LEDPARTS_MERGE": {},
    },
    "axe": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {"main_LED": {"id": 1, "len": 88}},
        "LEDPARTS_MERGE": {},
    },
    "staff": {
        "fps": 30,
        "OFPARTS": {},
        "LEDPARTS": {
            "skeleton_LED": {"id": 0, "len": 16},
            "stick_LED": {"id": 1, "len": 60},
            "snake_LED": {"id": 2, "len": 50},
            "eyes_LED": {"id": 3, "len": 6},
        },
        "LEDPARTS_MERGE": {},
    },
}
