//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ControlFrame")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub start: i32,
    pub fade: i8,
    pub meta_rev: i32,
    pub data_rev: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::control_data::Entity")]
    ControlData,
    #[sea_orm(has_one = "super::editing_control_frame::Entity")]
    EditingControlFrame,
}

impl Related<super::control_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ControlData.def()
    }
}

impl Related<super::editing_control_frame::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EditingControlFrame.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
