//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "LEDEffectState")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "LEDEffectState_effect_id_position_key")]
    pub effect_id: i32,
    #[sea_orm(unique_key = "LEDEffectState_effect_id_position_key")]
    pub position: i32,
    pub color_id: i32,
    pub alpha: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::led_effect::Entity",
        from = "Column::EffectId",
        to = "super::led_effect::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    LedEffect,
}

impl Related<super::led_effect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedEffect.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
